import { Quicksand } from 'next/font/google';
import "./globals.css";

const quicksand = Quicksand({
  weight: ["400", "700"],
  variable:"--font-quicksand",
  subsets: ['latin']
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={quicksand.className}>
        {children}
      </body>
    </html>
  );
}
